Fix wrong packaging of translators in xpi package
  * The included minimal Zotero distribution is now based on the
    latest stable branch (version 4.0.12) rather than on the master
    branch at some arbitrary point in time.

  * For an xpi-package, the Zotero translators need to be included
    in a different way: They need to be in a zipfile which is itself
    included in the (zipped) xpi file. This was not done in v0.2beta1
    with the effect that Dontprint could not install any translators
    and therefore did not work in a Firefox profile where neither a
    source version of Dontprint nor Zotero had ever been installed
    before. This commit fixes this issue.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,15 +1,49 @@
 #!/bin/bash
 
-INPUTFILES='install.rdf chrome.manifest icon.png defaults modules components chrome COPYING'
+INPUTFILES='install.rdf chrome.manifest icon.png defaults modules components chrome translators.zip translators.index deleted.txt COPYING'
 OUTPUTFILE='dontprint.xpi'
 
 PROGNAME=$(basename $0)
+PROGDIR=$(cd $(dirname $0); pwd)
 
 if [ -e $OUTPUTFILE ]; then
     echo "${PROGNAME}: File $OUTPUTFILE already exists." 1>&2
     exit 1
 fi
 
+if [ ! -d translators ]; then
+    echo "${PROGNAME}: Could not find translators" 1>&2
+    exit 1
+fi
+
+echo $PROGDIR
+
+# Build translators.zip and translators.index
+# (This is adapted from the file "build_xpi_4.0" in https://github.com/zotero/zotero-xpi-build.)
+rm translators.zip translators.index
+cd translators
+mkdir output
+mv deleted.txt $PROGDIR
+counter=0;
+for file in *.js; do
+	newfile=$counter.js;
+	id=`grep -m 1 '"translatorID"\s*:\s*"' "$file" | sed -r 's/.*"translatorID"\s*:\s*"(.*)".*/\1/'`
+	label=`grep -m 1 '"label"\s*:\s*"' "$file" | sed -r 's/.*"label"\s*:\s*"(.*)".*/\1/'`
+	mtime=`grep -m 1 '"lastUpdated"\s*:\s*"' "$file" | sed -r 's/.*"lastUpdated"\s*:\s*"(.*)".*/\1/'`
+	echo $newfile,$id,$label,$mtime >> $PROGDIR/translators.index
+	cp "$file" output/$newfile;
+	counter=$(($counter+1))
+done;
+cd output
+zip $PROGDIR/translators.zip *
+cd $PROGDIR
+rm -rf translators/output
+
+# create package
 zip -r $OUTPUTFILE $INPUTFILES
+
+# clean up
+mv deleted.txt translators
+rm translators.zip translators.index
 
 echo "${PROGNAME}: done; output in $OUTPUTFILE"
